// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AssetManager.Model;

public partial class Assignment
{
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int AssignmentId { get; set; }

    [DisplayName("Employee ID")]
    public int? EmployeeId { get; set; }

    [DisplayName("Asset ID")]
    public int? AssetId { get; set; }

    [DisplayName("Contract ID")]
    public int? ContractId { get; set; }

    [DisplayName("Assignment Date")]
    [DataType(DataType.Date)]
    public DateTime? AssignmentDate { get; set; }

    [DisplayName("Return Date")]
    [DataType(DataType.Date)]
    public DateTime? ReturnDate { get; set; }

    [DisplayName("Status")]
    public string Status { get; set; }

    [DisplayName("Change Log ID")]
    public int? ChangeLogId { get; set; }

    public virtual Asset Asset { get; set; }

    public virtual ChangeLog ChangeLog { get; set; }

    public virtual Contract Contract { get; set; }

    public virtual Employee Employee { get; set; }
}
