// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace AssetManager.Model;

public partial class Contract
{
    public int ContractId { get; set; }

    [DisplayName("Contract Provider")]
    public string Provider { get; set; }

    [DisplayName("Phone Number")]
    public string PhoneNumber { get; set; }

    [DisplayName("PIN Number")]
    public string Pinnumber { get; set; }

    [DisplayName("PUK Number")]
    public string Puknumber { get; set; }

    [DisplayName("Contract Start Date")]
    [DataType(DataType.Date)]
    public DateTime? ContractStartDate { get; set; }

    [DisplayName("Contract End Date")]
    [DataType(DataType.Date)]
    public DateTime? ContractEndDate { get; set; }

    [DisplayName("Monthly Cost")]
    public decimal? MonthlyCost { get; set; }

    [DisplayName("Data Limit")]
    public string DataLimit { get; set; }

    public virtual ICollection<Assignment> Assignments { get; set; } = new List<Assignment>();
}
