// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AssetManager.Model;

public partial class ContractOverview
{
    public int ContractId { get; set; }

    public DateTime? ActivatedOn { get; set; }

    public DateTime? ActiveUntil { get; set; }

    public string ContractStatus { get; set; }

    public DateTime? AssignedOn { get; set; }

    public string AssignedTo { get; set; }

    public DateTime? LastChangeDate { get; set; }

    public string ChangeDescription { get; set; }
}