// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;

namespace AssetManager.Model;

public partial class Employee
{
    public int EmployeeId { get; set; }

    [DisplayName("Global ID")]
    public string GlobalId { get; set; }

    [DisplayName("First Name")]
    public string FirstName { get; set; }

    [DisplayName("Last Name")]
    public string LastName { get; set; }

    [DisplayName("Email")]
    public string Email { get; set; }

    [DisplayName("Department")]
    public string Department { get; set; }

    [DisplayName("Position")]
    public string Position { get; set; }

    public virtual ICollection<Assignment> Assignments { get; set; } = new List<Assignment>();
}
