// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AssetManager.Model;

public partial class MobilePhoneOverview
{
    public int AssetId { get; set; }

    public string Brand { get; set; }

    public string Model { get; set; }

    public string SerialNumber { get; set; }

    public string Imeinumber1 { get; set; }

    public string Imeinumber2 { get; set; }

    public string Accessories { get; set; }

    public string Capacity { get; set; }

    public string AssetStatus { get; set; }

    public DateTime? PurchaseDate { get; set; }

    public DateTime? WarrantyExpiryDate { get; set; }

    public DateTime? HandoutDate { get; set; }

    public string HandoutTo { get; set; }

    public DateTime? LastChangeDate { get; set; }

    public string ChangeDescription { get; set; }
}