// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AssetManagerOctoberFinal.Model;

public partial class Assignment
{
    public int AssignmentId { get; set; }

    public int? EmployeeId { get; set; }

    public int? AssetId { get; set; }

    public int? ContractId { get; set; }

    public DateTime? AssignmentDate { get; set; }

    public DateTime? ReturnDate { get; set; }

    public string Status { get; set; }

    public int? ChangeLogId { get; set; }

    public virtual Asset Asset { get; set; }

    public virtual ChangeLog ChangeLog { get; set; }

    public virtual Contract Contract { get; set; }

    public virtual Employee Employee { get; set; }
}