// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AssetManagerOctoberFinal.Model;

public partial class Contract
{
    public int ContractId { get; set; }

    public string Provider { get; set; }

    public string PhoneNumber { get; set; }

    public string Pinnumber { get; set; }

    public string Puknumber { get; set; }

    public DateTime? ContractStartDate { get; set; }

    public DateTime? ContractEndDate { get; set; }

    public decimal? MonthlyCost { get; set; }

    public string DataLimit { get; set; }

    public virtual ICollection<Assignment> Assignments { get; set; } = new List<Assignment>();
}