// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AssetManagerOctoberFinal.Model;

public partial class Employee
{
    public int EmployeeId { get; set; }

    public string GlobalId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Email { get; set; }

    public string Department { get; set; }

    public string Position { get; set; }

    public virtual ICollection<Assignment> Assignments { get; set; } = new List<Assignment>();
}