// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AssetManagerOctoberFinal.Model;

public partial class EurssMobileAssetCsv
{
    public string AssetSerialNumber { get; set; }

    public string AssetBrand { get; set; }

    public string AssetModelName { get; set; }

    public string AssetModelNumber { get; set; }

    public string AssetSerialNumber2 { get; set; }

    public long? AssetImei1Number { get; set; }

    public string AssetImei2Number { get; set; }

    public string AssetCapacity { get; set; }

    public string Accessories { get; set; }

    public string AssetStatus { get; set; }

    public string Assignee { get; set; }

    public string AssigneeGlobalId { get; set; }

    public string GivenBy { get; set; }

    public string FormSignedAndFiled { get; set; }

    public string AssigneePhoneNumber { get; set; }

    public string GsmPackage { get; set; }

    public string GsmContractStartingDate { get; set; }

    public string GsmContractEndDate { get; set; }

    public string Pin { get; set; }

    public string Puk { get; set; }

    public string Pin2 { get; set; }

    public string Puk2 { get; set; }

    public DateTime? AssigneeCheckIn { get; set; }

    public DateTime? AssigneeCheckOut { get; set; }

    public string AssigneeNotes { get; set; }

    public byte? ExpectedDaysOfUse { get; set; }

    public DateTime? AssetDueDate2y { get; set; }

    public string AssetCondition { get; set; }

    public DateTime? DateConditionLastEvaluated { get; set; }

    public string Spirit { get; set; }

    public string Department { get; set; }

    public string DepartmentFinancialCode { get; set; }

    public string AssetType { get; set; }

    public string LastMaintenanceCheck { get; set; }

    public string NextMaintenanceCheck { get; set; }

    public string WarrantyExpirationDate { get; set; }

    public string AssetCost { get; set; }

    public string DateOfPurchase { get; set; }

    public string VendorName { get; set; }

    public string VendorContactInfo { get; set; }

    public string ServiceDeliveryDate { get; set; }

    public string ServiceReturnDate { get; set; }

    public string ServiceTrackingNumber { get; set; }
}