// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace AssetManagerOctoberFinal.Model
{
    public partial class GetPhoneDetailsResult
    {
        public int AssetID { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public DateTime? AssignmentDate { get; set; }
        public DateTime? ReturnDate { get; set; }
        [Column("Assigned To")]
        public string AssignedTo { get; set; }
        [Column("Last Change Date")]
        public DateTime? LastChangeDate { get; set; }
        [Column("Change Description")]
        public string ChangeDescription { get; set; }
    }
}
