// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AssetManagerOctoberFinal.Model;

public partial class UserContractAssignment
{
    public int UserId { get; set; }

    public string Username { get; set; }

    public int? ContractId { get; set; }

    public string PhoneNumber { get; set; }

    public DateTime? AssignmentDate { get; set; }

    public DateTime? ReturnDate { get; set; }

    public DateTime? LastChangeDate { get; set; }

    public string ChangeDescription { get; set; }
}